- name: "good first issue"
  color: 5319e7
  description: "Good for newcomers"
  aliases: []
- name: "help wanted"
  color: 008672
  description: "Extra attention is needed"
  aliases: []
- name: "âš™ï¸ DevOps"
  color: 008672
- name: "ğŸ§Š Ice Box "
  color: 008672
- name: "ğŸª Epic"
  color: "008672"
- name: "ğŸ†• Feature Request"
  color: "008672"
- name: "ğŸ–¼ï¸ Front End"
  color: "008672"
- name: "ğŸ„ Back End"
  color: "008672"
- name: "âš–ï¸ Compliance/Legal"
  color: "008672"
- name: "ğŸ¤  Something Fun"
  color: "008672"
- name: "ğŸ° Security "
  color: "008672"
- name: "ğŸ”Œ Integrations/API"
  color: "008672"
- name: "ğŸ—³ï¸ Feedback Needed "
  color: "008672"
- name: "â›” Blocked "
  color: "008672"
- name: "â™¿ Accessability"
  color: "008672"
- name: "ğŸŒµ Tough Issue"
  color: "008672"
- name: "ğŸš· Not Persuingó £ "
  color: "008672"
- name: "ğŸ—ï¸ In Progress "
  color: "008672"
- name: "ğŸ›Ÿ Need Help"
  color: "008672"
- name: "ğŸ†˜ Fire Drill ğŸš’"
  color: "008672"
- name: "0ï¸âƒ£ Points "
  color: "008672"
- name: "1ï¸âƒ£ Point "
  color: "008672"
- name: "âŒ› Scheduled for Closure"
  color: "008672"
- name: "ğŸ”¬ Research"
  color: "008672"
- name: "ğŸšï¸ Abandoned Issue"
  color: "008672"
- name: "ğŸ¤· No Ownership"
  color: "008672"
- name: "ğŸšª Candidate for Closure"
  color: "008672"