- name: "good first issue"
  color: "5319e7"
  description: "Good for newcomers"
  aliases: []

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
  aliases: []



- name: "âš™ï¸ DevOps"

- name: "ğŸ§Š Ice Box "

- name: "ğŸª Epic"

- name: "ğŸ†• Feature Request"

- name: "ğŸ–¼ï¸ Front End"

- name: "ğŸ„ Back End"


- name: "âš–ï¸ Compliance/Legal"

- name: "ğŸ¤  "

- name: "ğŸ° Security "

- name: "ğŸ”Œ Integrations/API"

- name: "ğŸ—³ï¸ Feedback Needed "


- name: "â›” Blocked "


- name: "â™¿ Accessability"


- name: "ğŸŒµ Tough Issue"

- name: "ğŸš· Not Persuingó £ "


- name: "ğŸ—ï¸ In Progress "


- name: "ğŸ›Ÿ Need Help"


- name: "ğŸ†˜ Fire Drill ğŸš’"


- name: "0ï¸âƒ£ Points "


- name: "1ï¸âƒ£ Point "


- name: "âŒ› Scheduled for Closure"


- name: "ğŸ”¬ Research"


- name: "ğŸšï¸ Abandoned Issue"

- name: "ğŸ¤· No Ownership"

- name: "ğŸšª Candidate for Closure"




